-- Snowflake user and resource creation for DBT transformations

-- Step 1: Use an admin role
USE ROLE ACCOUNTADMIN;

-- Step 2: Create the `transform` role and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Step 3: Create a default warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Step 4: Create the `epc_dbt` user and assign to the transform role
CREATE USER IF NOT EXISTS epc_dbt
  PASSWORD='epc_dbt#123'
  LOGIN_NAME='epc_dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_NAMESPACE='EPC_DB.RAW'
  COMMENT='DBT user used for data transformation for EPC pipeline project';
ALTER USER epc_dbt SET TYPE = LEGACY_SERVICE; -- meant for automation (not a human login)
GRANT ROLE TRANSFORM TO USER epc_dbt;

-- Step 5: Create a database and schema for the MovieLens project
CREATE DATABASE IF NOT EXISTS EPC_DB;
CREATE SCHEMA IF NOT EXISTS EPC_DB.RAW;

-- Step 6: Grant permissions to the `transform` role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE EPC_DB TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE EPC_DB TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE EPC_DB TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA EPC_DB.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA EPC_DB.RAW TO ROLE TRANSFORM;